#!/bin/bash

# python generate_graphs.py

iter_num=1
for filename in $(ls tspgraphs)
do
    if [ "$filename" != hc ] && [ "$filename" != no-hc ] ; then
        ./concorde "tspgraphs/$filename" > concorde_output
        opt=`sed -n -e "s/^\(.*\)\(Optimal Solution: \)\(.*\)\(\.\)\(.*\)/\3/p" concorde_output`
        size=`sed -n -e "s/^\(.*\)\(Number of Nodes: \)\(.*\)/\3/p" concorde_output`

        if [ "$opt" -eq "$size" ]
        then
            mv "tspgraphs/$filename" tspgraphs/hc
            # echo equal!
        else
            mv "tspgraphs/$filename" tspgraphs/no-hc
            # echo not equal!
        fi
        echo $iter_num
        let "iter_num++"
    fi
done
